name: deploy to azure1
on:
  push:
    branches:
      - dev-branch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout github repo
        uses: actions/checkout@v2
      - name: login azure
        uses: azure/login@v1
        with:
          creds: ${{secrets.AZURE_CREDENTIALS}}
      - name: setup azure cli
        uses: azure/aks-set-context@v1
        with:
          creds: ${{secrets.AZURE_CREDENTIALS}}
          resource-group: my-resource-group
           
      - name: deploy to aks
        run: |
          kubectl apply -f ./kubernetes/namespace.yaml
          kubectl apply -f ./kubernetes/deployment.yaml
          kubectl apply -f ./kubernetes/service.yaml
          kubectl apply -f ./release/kubernetes.manifest.yaml
