name: build docker images
on:
 push:
   branches:
     - dev-branch 
jobs:
  build:
   runs-on: ubuntu-latest
   steps:
     - name: checkout action
       uses: actions/checkout@v2 
     - name: login docker hub 
       uses: docker/login@v1 
       with:
        username: ${{secrets.DOCKER_USERNAME}}
        password: ${{secrets.DOCKER_PASSWORD}}
     - name: build docker image 
       run: docker build -t my-image .
     - name: run image 
       run: docker run -d -p 6060:80 my-image 
     - name: tag image 
       run: docker tag my-image:latest betrand1997/my-image:latest
     - name: push the image 
       run: docker push betrand1997/my-image:latest

