name: build and push docker image
on:
  push:
    branches:
      - dev-branch
jobs:
  build:
    runs-on: ubuntu-latest 
    steps:
      - name: checkout github repo 
        uses: actions/checkout@v2
      - name: login docker
        uses: docker/login-action@v2
        with:
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_PASSWORD}}
      - name: build image
        run: docker build -t myapp .
      - name: run docker image 
        run: docker run -d -p 6060:80 myapp
      - name: get public IP
        id: get_ip
        run: echo "::set-output name=public_ip::$(curl -s ifconfig.me)"
      - name: tag image 
        run: docker tag myapp betrand1997/myapp:latest
      - name: push image 
        run: docker push betrand1997/myapp:latest
